; ==============================
; Folder Actions Plugin
; ==============================
; Standardized and Enhanced

; ==============================
; HELPER FUNCTIONS
; ==============================

GetFolderDataPath() {
    dataPath := "data\\folder_data.ini"
    SplitPath(dataPath, , &dir)
    if !DirExist(dir)
        DirCreate(dir)
    return dataPath
}

GenerateShortcutsFile() {
    iniFile := GetFolderDataPath()
    history := LoadHistory("CustomFolders", iniFile)
    content := "; ===================================================================`n"
    content .= "; AUTO-GENERATED FILE - DO NOT EDIT`n"
    content .= "; Generated by folder_actions.ahk`n"
    content .= "; ===================================================================`n`n"
    
    if (history.Length > 0) {
        ; Register category for Recent Folders (Leader -> f -> h)
        content .= 'RegisterCategoryKeymap("leader", "f", "h", "Recent Folders", ' . Min(history.Length, 9) . ')`n'
        
        for index, path in history {
            if (index > 9)
                break
                
            ; Get folder name for description
            SplitPath(path, &folderName)
            if (folderName == "") ; Handle root drives like C:\
                folderName := path
            
            ; Escape backslashes for the path string
            escapedPath := StrReplace(path, "\", "\\")
            description := StrReplace(folderName, '"', '\"')
            
            ; Generate the keymap registration line using ShellExec
            content .= 'RegisterKeymap("leader", "f", "h", "' . index . '", "' . description . '", ShellExec("explorer .", "' . escapedPath . '", "Hide"), false, ' . index . ')`n'
        }
    }
    
    ; Determine path: same directory as this script
    SplitPath(A_LineFile, , &dir)
    targetFile := dir . "\folder_shortcuts.ahk"
    
    try {
        if FileExist(targetFile)
            FileDelete(targetFile)
        FileAppend(content, targetFile)
    } catch as err {
        ; Silently fail or log if needed, but avoid interrupting user flow
    }
}

RunFolderCommand(cmd, title := "Folder Command") {
    try {
        ShowCenteredToolTip("Running " . title)
        SetTimer(() => RemoveToolTip(), -1500)
    }
    Run(cmd)
}

; ==============================
; GUI FUNCTIONS
; ==============================

ShowCustomFolderGui() {
    g := Gui(, "Open Folder")
    g.SetFont("s10", "Segoe UI")
    
    g.Add("Text",, "Enter or Select Folder Path:")
    
    iniFile := GetFolderDataPath()
    history := LoadHistory("CustomFolders", iniFile)
    cb := g.Add("ComboBox", "w400 vPath", history)
    if (history.Length > 0)
        cb.Text := history[1]
        
    g.Add("Button", "Default w80", "Open").OnEvent("Click", (*) => OpenCustom(g, cb.Text))
    g.Add("Button", "x+10 w80", "Browse").OnEvent("Click", (*) => BrowseFolder(cb))
    
    g.Show()
    
    BrowseFolder(comboBoxObj) {
        selected := DirSelect(comboBoxObj.Text, 3, "Select Folder")
        if (selected != "")
            comboBoxObj.Text := selected
    }
    
    OpenCustom(guiObj, path) {
        if (path == "")
            return
            
        if !DirExist(path) {
            MsgBox("Folder does not exist:`n" . path, "Error", "Icon!")
            return
        }
            
        guiObj.Destroy()
        iniFile := GetFolderDataPath()
        SaveHistory("CustomFolders", path, iniFile)
        GenerateShortcutsFile()
        RunFolderCommand('explorer.exe "' . path . '"', "Opening " . path)
    }
}

; ==============================
; ACTION FUNCTIONS
; ==============================

OpenTempFolder() {
    RunFolderCommand('explorer.exe "' . EnvGet("TEMP") . '"', "Temp Folder")
}

OpenAppDataFolder() {
    RunFolderCommand('explorer.exe "' . EnvGet("APPDATA") . '"', "AppData")
}

OpenProgramFilesFolder() {
    RunFolderCommand('explorer.exe "C:\Program Files"', "Program Files")
}

OpenUserProfileFolder() {
    RunFolderCommand('explorer.exe "' . EnvGet("USERPROFILE") . '"', "User Profile")
}

OpenDesktopFolder() {
    RunFolderCommand('explorer.exe "' . EnvGet("USERPROFILE") . '\Desktop"', "Desktop")
}

OpenSystem32Folder() {
    RunFolderCommand('explorer.exe "C:\Windows\System32"', "System32")
}

OpenCustomFolder() {
    ShowCustomFolderGui()
}

OpenInTerminal() {
    path := GetActiveExplorerPath()
    if (path == "")
        path := A_WorkingDir
        
    ; Try to use Windows Terminal (wt.exe) if available, else cmd
    try {
        RunFolderCommand('wt.exe -d "' . path . '"', "Terminal in " . path)
    } catch {
        RunFolderCommand('cmd.exe /k cd /d "' . path . '"', "Terminal in " . path)
    }
}

CopyFolderPath() {
    path := GetActiveExplorerPath()
    if (path != "") {
        A_Clipboard := path
        ShowCenteredToolTip("Copied: " . path)
        SetTimer(() => RemoveToolTip(), -1500)
    } else {
        ShowCenteredToolTip("No folder active")
        SetTimer(() => RemoveToolTip(), -1500)
    }
}

; ===================================================================
; DEFAULT KEYMAPS
; ===================================================================
; These keymaps are auto-registered when this plugin is loaded.

; Folder Access (leader → f → KEY)
RegisterCategoryKeymap("leader", "f", "Folder Actions", 9)
RegisterKeymap("leader", "f", "t", "Temp Folder", OpenTempFolder, false, 1)
RegisterKeymap("leader", "f", "a", "AppData", OpenAppDataFolder, false, 2)
RegisterKeymap("leader", "f", "p", "Program Files", OpenProgramFilesFolder, false, 3)
RegisterKeymap("leader", "f", "u", "User Profile", OpenUserProfileFolder, false, 4)
RegisterKeymap("leader", "f", "d", "Desktop", OpenDesktopFolder, false, 5)
RegisterKeymap("leader", "f", "s", "System32", OpenSystem32Folder, false, 6)
RegisterKeymap("leader", "f", "o", "Open Custom", OpenCustomFolder, false, 7)
RegisterKeymap("leader", "f", "T", "Term Here", OpenInTerminal, false, 8)
RegisterKeymap("leader", "f", "y", "Copy Path", CopyFolderPath, false, 9)
